# Generated by Django 6.0.4 on 2026-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discounts",
            field=models.PositiveIntegerField(
                default=0, help_text="Enter percentage (e.g., 10 for 10%)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="actual_price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.CharField(max_length=100),
        ),
    ]
