# Generated by Django 6.0.4 on 2026-04-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_discounts_alter_product_actual_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRONICS", "Electronics"),
                    ("CLOTHING", "Clothing"),
                    ("HOME_KITCHEN", "Home & Kitchen"),
                    ("BEAUTY", "Beauty"),
                    ("SPORTS", "Sports"),
                    ("BOOKS", "Books"),
                    ("TOYS", "Toys"),
                    ("AUTOMOTIVE", "Automotive"),
                    ("GROCERY", "Grocery"),
                    ("ACCESSORIES", "Accessories"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.CharField(
                choices=[
                    ("MOBILE", "Mobile Phones"),
                    ("LAPTOP", "Laptops"),
                    ("MENS_WEAR", "Men's Wear"),
                    ("WOMENS_WEAR", "Women's Wear"),
                    ("FURNITURE", "Furniture"),
                    ("DECOR", "Home Decor"),
                    ("SKINCARE", "Skincare"),
                    ("FRAGRANCE", "Fragrance"),
                    ("EQUIPMENT", "Sports Equipment"),
                    ("FICTION", "Fiction Books"),
                ],
                max_length=20,
            ),
        ),
    ]
