# Generated by Django 6.0.4 on 2026-04-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_category_alter_product_sub_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="marked_price",
            new_name="market_price",
        ),
    ]
