# Generated by Django 6.0.4 on 2026-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_rename_marked_price_product_market_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="market_price",
            new_name="marked_price",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
