# Generated by Django 6.0.4 on 2026-05-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_rename_market_price_product_marked_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitems",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitems",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orderitemtracking",
            name="item",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItems",
        ),
        migrations.DeleteModel(
            name="OrderItemTracking",
        ),
    ]
