# Generated by Django 6.0.4 on 2026-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivery_charge_order_is_bazar_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemtracking",
            name="platform_earning",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitemtracking",
            name="platform_fee_percentage",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="orderitemtracking",
            name="seller_earning",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
