# Generated by Django 6.0.4 on 2026-05-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_orderitemtracking_platform_earning_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitemtracking",
            options={"ordering": ["timestamp"]},
        ),
    ]
