# Generated by Django 6.0.4 on 2026-05-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_orderitemtracking_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="is_visible_to_seller",
            field=models.BooleanField(default=True),
        ),
    ]
