# Generated by Django 6.0.4 on 2026-04-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_approved_seller",
            field=models.BooleanField(default=False),
        ),
    ]
