# Generated by Django 6.0.4 on 2026-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_approved_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="product_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sub_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
