# Generated by Django 6.0.4 on 2026-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_product_category_customuser_sub_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="product_category",
        ),
        migrations.AddField(
            model_name="customuser",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRONICS", "Electronics"),
                    ("CLOTHING", "Clothing"),
                    ("HOME_KITCHEN", "Home & Kitchen"),
                    ("BEAUTY", "Beauty"),
                    ("SPORTS", "Sports"),
                    ("BOOKS", "Books"),
                    ("TOYS", "Toys"),
                    ("AUTOMOTIVE", "Automotive"),
                    ("GROCERY", "Grocery"),
                    ("ACCESSORIES", "Accessories"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sub_category",
            field=models.CharField(
                choices=[
                    ("MOBILE", "Mobile Phones"),
                    ("LAPTOP", "Laptops"),
                    ("MENS_WEAR", "Men's Wear"),
                    ("WOMENS_WEAR", "Women's Wear"),
                    ("FURNITURE", "Furniture"),
                    ("DECOR", "Home Decor"),
                    ("SKINCARE", "Skincare"),
                    ("FRAGRANCE", "Fragrance"),
                    ("EQUIPMENT", "Sports Equipment"),
                    ("FICTION", "Fiction Books"),
                ],
                default="1",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
